-- ロードホイールの拡充: 既存13件のフリーボディ補完と主要ブランドの新規追加
-- 価格は日本の正規販売店/公式の税込価格、重量はメーカー公表値または正規販売店表記
PRAGMA foreign_keys = ON;

-- 未登録ブランド
INSERT INTO brands (id, name, created_at, updated_at) VALUES (92, 'Syncros', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO brands (id, name, created_at, updated_at) VALUES (93, 'Miche', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- A. 既存ホイールの freehub_body を補完する (13件)
INSERT INTO part_specifications (part_id, spec_key, spec_value, created_at, updated_at) VALUES
    (117, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (118, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (119, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (120, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (121, 'freehub_body', 'campagnolo_n3w,shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (122, 'freehub_body', 'campagnolo_n3w,shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (123, 'freehub_body', 'campagnolo_n3w,shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (124, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (125, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (126, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (127, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (128, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (550, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- B. 新規ロードホイール (id 558-584)
INSERT INTO parts (price, weight, brand_id, category_id, created_at, id, price_updated_at, updated_at, model_name, name, variant_name, description) VALUES
    (409420, 1390, 42, 13, CURRENT_TIMESTAMP, 558, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Vision Metron 45 SL', 'Vision Metron 45 SL Disc Wheelset', NULL, '45mmハイトのオールラウンド・エアロホイール。重量は前後合計の公表値です'),
    (420640, 1490, 42, 13, CURRENT_TIMESTAMP, 559, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Vision Metron 60 SL', 'Vision Metron 60 SL Disc Wheelset', NULL, '60mmハイトのエアロホイール。重量は前後合計の公表値です'),
    (671000, 1170, 92, 13, CURRENT_TIMESTAMP, 560, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Syncros Capital SL 40', 'Syncros Capital SL 40 Wheelset', NULL, 'リム・ハブ一体成型の40mmハイトホイール。重量は前後合計の公表値です'),
    (693000, 1290, 92, 13, CURRENT_TIMESTAMP, 561, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Syncros Capital SL Aero 60', 'Syncros Capital SL Aero 60 Wheelset', NULL, 'リム・ハブ一体成型の60mmハイトエアロホイール。重量は前後合計の公表値です'),
    (264000, 1249, 47, 13, CURRENT_TIMESTAMP, 562, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'CADEX Max 40 Disc', 'CADEX Max 40 Disc Tubeless Wheelset', NULL, 'カーボンスポーク一体型ハブの40mmハイトホイール。重量はShimanoフリー時の公表値です'),
    (264000, 1290, 47, 13, CURRENT_TIMESTAMP, 563, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'CADEX Max 50 Disc', 'CADEX Max 50 Disc Tubeless Wheelset', NULL, 'カーボンスポーク一体型ハブの50mmハイトホイール。重量はテープ・バルブ込みの公表値です'),
    (667700, 1325, 28, 13, CURRENT_TIMESTAMP, 564, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Campagnolo Bora Ultra WTO 45', 'Campagnolo Bora Ultra WTO 45 Disc Wheelset', NULL, 'CULTベアリングの45mmハイトホイール。重量は前後合計の公表値です'),
    (667700, 1240, 28, 13, CURRENT_TIMESTAMP, 565, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Campagnolo Hyperon Ultra', 'Campagnolo Hyperon Ultra Disc Wheelset', NULL, '37mmハイトの超軽量ヒルクライムホイール。重量は前後合計の公表値です'),
    (431200, 1285, 15, 13, CURRENT_TIMESTAMP, 566, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Fulcrum Speed 25 DB', 'Fulcrum Speed 25 DB Wheelset', NULL, '26mmハイトの軽量ヒルクライムホイール。重量は前後合計の公表値です'),
    (228800, 1590, 15, 13, CURRENT_TIMESTAMP, 567, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Fulcrum Racing Zero DB', 'Fulcrum Racing Zero DB Wheelset', NULL, '30mmハイトのアルミリムホイール。重量は前後合計の公表値です'),
    (918500, 1260, 16, 13, CURRENT_TIMESTAMP, 568, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Mavic Cosmic Ultimate 45 Disc 23mm', 'Mavic Cosmic Ultimate 45 Disc 23mm Wheelset', NULL, 'R2Rカーボンスポークの45mmハイトホイール。重量は前後合計の公表値です'),
    (384585, 1753, 27, 13, CURRENT_TIMESTAMP, 569, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'DT Swiss ARC 1100 DICUT 80 DB', 'DT Swiss ARC 1100 DICUT 80 DB Wheelset', NULL, '80mmハイトのTT・トライアスロン向けエアロホイール。重量は前後合計の公表値です'),
    (384585, 1449, 27, 13, CURRENT_TIMESTAMP, 570, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'DT Swiss ERC 1100 DICUT 45 DB', 'DT Swiss ERC 1100 DICUT 45 DB Wheelset', NULL, '45mmハイトのエンデュランス向けホイール。重量は前後合計の公表値です'),
    (818100, 1500, 23, 13, CURRENT_TIMESTAMP, 571, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Zipp 858 NSW Tubeless Disc', 'Zipp 858 NSW Tubeless Disc Wheelset', NULL, 'Sawtoothリムのディープエアロホイール。重量はバルブ・テープ込みの公表値です'),
    (398700, 1635, 23, 13, CURRENT_TIMESTAMP, 572, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Zipp 808 Firecrest Tubeless Disc', 'Zipp 808 Firecrest Tubeless Disc Wheelset', NULL, '80mmハイトのエアロホイール。重量は前後合計の公表値です'),
    (299860, 1535, 26, 13, CURRENT_TIMESTAMP, 573, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'ENVE 45 Innerdrive', 'ENVE Foundation 45 Innerdrive Wheelset', NULL, 'Foundationシリーズの45mmハイトホイール。重量は前後合計の公表値です'),
    (299860, 1635, 26, 13, CURRENT_TIMESTAMP, 574, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'ENVE 65 Innerdrive', 'ENVE Foundation 65 Innerdrive Wheelset', NULL, 'Foundationシリーズの65mmハイトホイール。重量は前後合計の公表値です'),
    (323950, 1325, 50, 13, CURRENT_TIMESTAMP, 575, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Bontrager Aeolus RSL 37', 'Bontrager Aeolus RSL 37 TLR Disc Wheelset', NULL, '37mmハイトの軽量オールラウンドホイール。重量は前後合計の公表値です'),
    (369800, 1410, 50, 13, CURRENT_TIMESTAMP, 576, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Bontrager Aeolus RSL 51', 'Bontrager Aeolus RSL 51 TLR Disc Wheelset', NULL, '51mmハイトのオールラウンド・エアロホイール。重量は前後合計の公表値です'),
    (323950, 1520, 50, 13, CURRENT_TIMESTAMP, 577, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Bontrager Aeolus RSL 62', 'Bontrager Aeolus RSL 62 TLR Disc Wheelset', NULL, '62mmハイトのスプリンター向けエアロホイール。重量は前後合計の公表値です'),
    (323950, 1645, 50, 13, CURRENT_TIMESTAMP, 578, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Bontrager Aeolus RSL 75', 'Bontrager Aeolus RSL 75 TLR Disc Wheelset', NULL, '75mmハイトのTT・トライアスロン向けホイール。重量は前後合計の公表値です'),
    (383900, 1354, 48, 13, CURRENT_TIMESTAMP, 579, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Reserve 34|37 TA', 'Reserve 34|37 TA Wheelset', NULL, '前34mm/後37mmのオールラウンドホイール。重量はDT240使用時の公表値です'),
    (484000, 1305, 49, 13, CURRENT_TIMESTAMP, 580, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Roval Rapide CLX III', 'Roval Rapide CLX III Wheelset', NULL, '前51mm/後48mmのエアロホイール。重量はバルブ・テープ込みの公表値です'),
    (451000, 1131, 49, 13, CURRENT_TIMESTAMP, 581, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Roval Alpinist CLX III', 'Roval Alpinist CLX III Wheelset', NULL, '33mmハイトの超軽量ヒルクライムホイール。重量はバルブ・テープ込みの公表値です'),
    (176000, 1452, 7, 13, CURRENT_TIMESTAMP, 582, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Giant SLR 1 42 Disc', 'Giant SLR 1 42 Disc WheelSystem', NULL, '42mmハイトのフックレスカーボンホイール。重量は前後合計の公表値です'),
    (404800, 1390, 93, 13, CURRENT_TIMESTAMP, 583, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Miche Kleos RD 36', 'Miche Kleos RD 36 Wheelset', NULL, 'CeramicSpeedベアリングの36mmハイトホイール。重量はXDR仕様の公表値です'),
    (404800, 1455, 93, 13, CURRENT_TIMESTAMP, 584, '2026-09-12 00:00:00', CURRENT_TIMESTAMP, 'Miche Kleos RD 50', 'Miche Kleos RD 50 Wheelset', NULL, 'CeramicSpeedベアリングの50mmハイトホイール。重量はXDR仕様の公表値です');

-- C. 新規ホイールの規格 (すべて700C・センターロック)
INSERT INTO part_specifications (part_id, spec_key, spec_value, created_at, updated_at) VALUES
    (558, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (558, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (558, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (559, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (559, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (559, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (560, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (560, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (560, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (561, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (561, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (561, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (562, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (562, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (562, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (563, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (563, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (563, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (564, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (564, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (564, 'freehub_body', 'campagnolo_n3w,shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (565, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (565, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (565, 'freehub_body', 'campagnolo_n3w,shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (566, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (566, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (566, 'freehub_body', 'shimano_hg,campagnolo_n3w,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (567, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (567, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (567, 'freehub_body', 'shimano_hg,campagnolo_n3w,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (568, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (568, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (568, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (569, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (569, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (569, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (570, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (570, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (570, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (571, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (571, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (571, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (572, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (572, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (572, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (573, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (573, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (573, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (574, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (574, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (574, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (575, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (575, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (575, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (576, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (576, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (576, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (577, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (577, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (577, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (578, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (578, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (578, 'freehub_body', 'shimano_hg,sram_xdr,campagnolo_n3w', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (579, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (579, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (579, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (580, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (580, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (580, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (581, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (581, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (581, 'freehub_body', 'shimano_hg,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (582, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (582, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (582, 'freehub_body', 'shimano_hg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (583, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (583, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (583, 'freehub_body', 'shimano_hg,campagnolo_n3w,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (584, 'wheel_diameter', '700C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (584, 'rotor_mount', 'center_lock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (584, 'freehub_body', 'shimano_hg,campagnolo_n3w,sram_xdr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
